In [1]:
from datetime import datetime
import os
import time

import numpy as np
import pandas as pd

In [2]:

from sherlock.functional import extract_features_to_csv
from sherlock.features.paragraph_vectors import initialise_pretrained_model, initialise_nltk
from sherlock.features.preprocessing import (
    #extract_features,
    #convert_string_lists_to_lists,
    prepare_feature_extraction,
    load_parquet_values,
)
from sherlock.features.word_embeddings import initialise_word_embeddings

unable to import 'smart_open.gcs', disabling that module

In [3]:
print(f'Started at {datetime.now()}.')

Started at 2025-07-06 14:26:27.056008.

In [4]:
prepare_feature_extraction()

Preparing feature extraction by downloading 4 files:

 ../sherlock/features/glove.6B.50d.txt,
 ../sherlock/features/par_vec_trained_400.pkl.docvecs.vectors_docs.npy,

 ../sherlock/features/par_vec_trained_400.pkl.trainables.syn1neg.npy, and
 ../sherlock/features/par_vec_trained_400.pkl.wv.vectors.npy.

All files for extracting word and paragraph embeddings are present.

In [5]:
if not os.path.exists('../sherlock/features/par_vec_trained_400.pkl.docvecs.vectors_docs.npy'):
    raise SystemExit(
        """
        Trained paragraph vectors do not exist,
        please run the '01-train-paragraph-vector-features' notebook before continuing
        """
    )

In [6]:
# ensure embedding initialisation is outside of timing for extract_features
prepare_feature_extraction()
initialise_word_embeddings()
initialise_pretrained_model(400)
initialise_nltk()

Preparing feature extraction by downloading 4 files:

 ../sherlock/features/glove.6B.50d.txt,
 ../sherlock/features/par_vec_trained_400.pkl.docvecs.vectors_docs.npy,

 ../sherlock/features/par_vec_trained_400.pkl.trainables.syn1neg.npy, and
 ../sherlock/features/par_vec_trained_400.pkl.wv.vectors.npy.

All files for extracting word and paragraph embeddings are present.
Initialising word embeddings
Initialise Word Embeddings process took 0:00:03.849251 seconds.
Initialise Doc2Vec Model, 400 dim, process took 0:00:01.601259 seconds. (filename = ../sherlock/features/par_vec_trained_400.pkl)
Initialised NLTK, process took 0:00:00.106997 seconds.

[nltk_data] Downloading package punkt to /home/omadbek/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /home/omadbek/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [7]:
timestr = time.strftime("%Y%m%d-%H%M%S")

# Saving processed files
X_train_filename_csv = f'../none_data/processed/train_{timestr}.csv'
X_test_filename_csv = f'../none_data/processed/test_{timestr}.csv'
X_validation_filename_csv = f'../none_data/processed/validation_{timestr}.csv'

#X_test_synthetic_filename_csv = f'../custom_data/processed/test_synthetic_{timestr}.csv'

# Extract Features to csv file

### Training

In [8]:
values = load_parquet_values("../none_data/train_data.parquet")

extract_features_to_csv(X_train_filename_csv, values)

values = None

Starting ../none_data/processed/train_20250706-142639.csv at 2025-07-06 14:26:42.411150. Rows=744, using 64 CPU cores
Exporting 1588 column features
Finished. Processed 744 rows in 0:00:02.309699, key_count=8

### Validation

In [9]:
values = load_parquet_values("../none_data/validation_data.parquet")

extract_features_to_csv(X_validation_filename_csv, values)

values = None

Starting ../none_data/processed/validation_20250706-142639.csv at 2025-07-06 14:26:48.659140. Rows=93, using 64 CPU cores
Exporting 1588 column features
Finished. Processed 93 rows in 0:00:02.066514, key_count=1

### Test

In [10]:
values = load_parquet_values("../none_data/test_data.parquet")

extract_features_to_csv(X_test_filename_csv, values)

values = None

Starting ../none_data/processed/test_20250706-142639.csv at 2025-07-06 14:26:52.456383. Rows=94, using 64 CPU cores
Exporting 1588 column features
Finished. Processed 94 rows in 0:00:02.869468, key_count=1

## Read locally processed features

### Train

In [11]:
start = datetime.now()

X_train = pd.read_csv(X_train_filename_csv, dtype=np.float32)

#print(f'Load Features (test) process took {datetime.now() - start} seconds.')

In [12]:
X_train.head()

,n_[0]-agg-any,n_[0]-agg-all,n_[0]-agg-mean,n_[0]-agg-var,n_[0]-agg-min,n_[0]-agg-max,n_[0]-agg-median,n_[0]-agg-sum,n_[0]-agg-kurtosis,n_[0]-agg-skewness,...,par_vec_390,par_vec_391,par_vec_392,par_vec_393,par_vec_394,par_vec_395,par_vec_396,par_vec_397,par_vec_398,par_vec_399
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-3.0,0.0,...,-0.025171,-0.025547,-0.039649,0.039113,-0.014739,-0.002653,-0.024507,-0.048443,0.039438,-0.031517
1,1.0,1.0,106.0,0.0,106.0,106.0,106.0,106.0,-3.0,0.0,...,0.000796,-0.000720,-0.000064,-0.001042,-0.000857,0.000245,0.000250,-0.000785,-0.000372,-0.000578
2,1.0,1.0,516.0,0.0,516.0,516.0,516.0,516.0,-3.0,0.0,...,-0.000240,0.000873,0.000199,0.001025,0.000458,-0.000961,0.000428,0.001202,0.000635,-0.000554
3,1.0,1.0,8.0,0.0,8.0,8.0,8.0,8.0,-3.0,0.0,...,0.000227,0.000883,0.001054,0.000034,0.000965,-0.000837,-0.000434,-0.000899,0.000353,0.000269
4,1.0,1.0,33.0,0.0,33.0,33.0,33.0,33.0,-3.0,0.0,...,-0.000410,0.001089,0.001006,0.000569,-0.000798,0.001187,-0.000716,-0.000601,0.000288,0.000872

### Validation

In [13]:
start = datetime.now()

X_validation = pd.read_csv(X_validation_filename_csv, dtype=np.float32)

#print(f'Load Features (test) process took {datetime.now() - start} seconds.')

In [14]:
X_validation.head()

,n_[0]-agg-any,n_[0]-agg-all,n_[0]-agg-mean,n_[0]-agg-var,n_[0]-agg-min,n_[0]-agg-max,n_[0]-agg-median,n_[0]-agg-sum,n_[0]-agg-kurtosis,n_[0]-agg-skewness,...,par_vec_390,par_vec_391,par_vec_392,par_vec_393,par_vec_394,par_vec_395,par_vec_396,par_vec_397,par_vec_398,par_vec_399
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-3.0,0.0,...,0.000473,-0.000692,0.000470,0.000896,0.000561,-0.000648,-0.000147,0.001073,-0.001199,0.001135
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-3.0,0.0,...,-0.000718,-0.001033,0.001013,0.000872,-0.000641,-0.000027,-0.001149,-0.000649,0.000287,0.000028
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-3.0,0.0,...,-0.037258,-0.011502,-0.075071,0.005284,-0.048580,-0.051761,-0.030931,-0.031386,0.062047,-0.042751
3,1.0,1.0,130.0,0.0,130.0,130.0,130.0,130.0,-3.0,0.0,...,-0.000794,0.000463,-0.000850,0.000447,-0.000629,-0.001176,-0.000150,0.000280,0.001080,-0.000468
4,1.0,1.0,6.0,0.0,6.0,6.0,6.0,6.0,-3.0,0.0,...,0.000205,-0.000686,-0.000444,0.000507,-0.000470,-0.001085,-0.000116,-0.000821,0.001126,0.000998

### Test

In [15]:
start = datetime.now()

X_test = pd.read_csv(X_test_filename_csv, dtype=np.float32)

#print(f'Load Features (test) process took {datetime.now() - start} seconds.')

In [16]:
X_test.head()

,n_[0]-agg-any,n_[0]-agg-all,n_[0]-agg-mean,n_[0]-agg-var,n_[0]-agg-min,n_[0]-agg-max,n_[0]-agg-median,n_[0]-agg-sum,n_[0]-agg-kurtosis,n_[0]-agg-skewness,...,par_vec_390,par_vec_391,par_vec_392,par_vec_393,par_vec_394,par_vec_395,par_vec_396,par_vec_397,par_vec_398,par_vec_399
0,1.0,1.0,2.0,0.0,2.0,2.0,2.0,2.0,-3.0,0.0,...,-0.037579,-0.014566,-0.027265,-0.008413,-0.059270,-0.000220,0.018577,-0.037931,0.019503,-0.034533
1,1.0,1.0,30.0,0.0,30.0,30.0,30.0,30.0,-3.0,0.0,...,-0.000040,-0.001096,0.001204,-0.000704,0.000767,0.000355,-0.000022,-0.000939,-0.000248,-0.000030
2,1.0,1.0,138.0,0.0,138.0,138.0,138.0,138.0,-3.0,0.0,...,0.000823,0.000631,0.000697,0.000406,-0.000303,0.000308,0.000995,-0.000358,0.000540,0.000371
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-3.0,0.0,...,-0.000304,0.000955,0.000825,0.000954,0.000472,-0.001223,0.001080,-0.000486,0.001097,-0.001047
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-3.0,0.0,...,0.000631,-0.000431,0.001216,0.001016,-0.001084,0.000262,-0.000563,-0.000413,-0.000754,0.000568

## Impute NaN values with feature means

In [17]:
start = datetime.now()

train_columns_means = pd.DataFrame(X_train.mean()).transpose()

#print(f'Transpose process took {datetime.now() - start} seconds.')

In [18]:
start = datetime.now()

X_train.fillna(train_columns_means.iloc[0], inplace=True)
X_validation.fillna(train_columns_means.iloc[0], inplace=True)
X_test.fillna(train_columns_means.iloc[0], inplace=True)

#X_test_synthetic.fillna(train_columns_means.iloc[0], inplace=True)

train_columns_means=None

#print(f'FillNA process took {datetime.now() - start} seconds.')

In [19]:
import os

# list of target parquet files
paths = [
    '../none_data/processed/train.parquet',
    '../none_data/processed/validation.parquet',
    '../none_data/processed/test.parquet',
#    '../custom_data/processed/test_synthetic.parquet',
]

# remove any that already exist
for path in paths:
    if os.path.exists(path):
        os.remove(path)
        print(f"Removed existing file: {path}")

In [20]:
start = datetime.now()

X_train.to_parquet('../none_data/processed/train.parquet', engine='pyarrow', compression='snappy')
X_validation.to_parquet('../none_data/processed/validation.parquet', engine='pyarrow', compression='snappy')
X_test.to_parquet('../none_data/processed/test.parquet', engine='pyarrow', compression='snappy')

#X_test_synthetic.to_parquet('../custom_data/processed/test_synthetic.parquet', engine='pyarrow', compression='snappy')

#print(f'Save parquet process took {datetime.now() - start} seconds.')

In [21]:
print(f'Completed at {datetime.now()}.')

Completed at 2025-07-06 14:27:14.184155.