In [1]:
from datetime import datetime
import os
import time

import numpy as np
import pandas as pd

In [2]:

from sherlock.functional import extract_features_to_csv
from sherlock.features.paragraph_vectors import initialise_pretrained_model, initialise_nltk
from sherlock.features.preprocessing import (
    #extract_features,
    #convert_string_lists_to_lists,
    prepare_feature_extraction,
    load_parquet_values,
)
from sherlock.features.word_embeddings import initialise_word_embeddings

unable to import 'smart_open.gcs', disabling that module

In [3]:
print(f'Started at {datetime.now()}.')

Started at 2025-05-16 12:11:52.597990.

In [4]:
prepare_feature_extraction()

Preparing feature extraction by downloading 4 files:

 ../sherlock/features/glove.6B.50d.txt,
 ../sherlock/features/par_vec_trained_400.pkl.docvecs.vectors_docs.npy,

 ../sherlock/features/par_vec_trained_400.pkl.trainables.syn1neg.npy, and
 ../sherlock/features/par_vec_trained_400.pkl.wv.vectors.npy.

All files for extracting word and paragraph embeddings are present.

In [5]:
if not os.path.exists('../sherlock/features/par_vec_trained_400.pkl.docvecs.vectors_docs.npy'):
    raise SystemExit(
        """
        Trained paragraph vectors do not exist,
        please run the '01-train-paragraph-vector-features' notebook before continuing
        """
    )

In [6]:
# ensure embedding initialisation is outside of timing for extract_features
prepare_feature_extraction()
initialise_word_embeddings()
initialise_pretrained_model(400)
initialise_nltk()

Preparing feature extraction by downloading 4 files:

 ../sherlock/features/glove.6B.50d.txt,
 ../sherlock/features/par_vec_trained_400.pkl.docvecs.vectors_docs.npy,

 ../sherlock/features/par_vec_trained_400.pkl.trainables.syn1neg.npy, and
 ../sherlock/features/par_vec_trained_400.pkl.wv.vectors.npy.

All files for extracting word and paragraph embeddings are present.
Initialising word embeddings
Initialise Word Embeddings process took 0:00:02.602022 seconds.
Initialise Doc2Vec Model, 400 dim, process took 0:00:01.394606 seconds. (filename = ../sherlock/features/par_vec_trained_400.pkl)
Initialised NLTK, process took 0:00:00.182348 seconds.

[nltk_data] Downloading package punkt to /Users/omad/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /Users/omad/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [7]:
timestr = time.strftime("%Y%m%d-%H%M%S")

# Saving processed files
X_train_filename_csv = f'../custom_data/processed/train_{timestr}.csv'
X_test_filename_csv = f'../custom_data/processed/test_{timestr}.csv'
X_validation_filename_csv = f'../custom_data/processed/validation_{timestr}.csv'

#X_test_synthetic_filename_csv = f'../custom_data/processed/test_synthetic_{timestr}.csv'

# Extract Features to csv file

### Training

In [8]:
values = load_parquet_values("../custom_data/raw/train_data.parquet")

extract_features_to_csv(X_train_filename_csv, values)

values = None

Starting ../custom_data/processed/train_20250516-121209.csv at 2025-05-16 12:12:16.905494. Rows=146, using 10 CPU cores
Exporting 1588 column features
Finished. Processed 146 rows in 0:00:01.323591, key_count=2

### Validation

In [9]:
values = load_parquet_values("../custom_data/raw/validation_data.parquet")

extract_features_to_csv(X_validation_filename_csv, values)

values = None

Starting ../custom_data/processed/validation_20250516-121209.csv at 2025-05-16 12:12:20.562824. Rows=48, using 10 CPU cores
Exporting 1588 column features
Finished. Processed 48 rows in 0:00:00.693281, key_count=1

### Test

In [10]:
values = load_parquet_values("../custom_data/raw/test_data.parquet")

extract_features_to_csv(X_test_filename_csv, values)

values = None

Starting ../custom_data/processed/test_20250516-121209.csv at 2025-05-16 12:12:24.308900. Rows=50, using 10 CPU cores
Exporting 1588 column features
Finished. Processed 50 rows in 0:00:00.992900, key_count=1

### Synthetic Test

In [11]:
#values = load_parquet_values("../custom_data/raw/synthetic_test_data.parquet")

#extract_features_to_csv(X_test_synthetic_filename_csv, values)

#values = None

## Read locally processed features

### Train

In [12]:
start = datetime.now()

X_train = pd.read_csv(X_train_filename_csv, dtype=np.float32)

#print(f'Load Features (test) process took {datetime.now() - start} seconds.')

In [13]:
X_train.head()

,n_[0]-agg-any,n_[0]-agg-all,n_[0]-agg-mean,n_[0]-agg-var,n_[0]-agg-min,n_[0]-agg-max,n_[0]-agg-median,n_[0]-agg-sum,n_[0]-agg-kurtosis,n_[0]-agg-skewness,...,par_vec_390,par_vec_391,par_vec_392,par_vec_393,par_vec_394,par_vec_395,par_vec_396,par_vec_397,par_vec_398,par_vec_399
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-3.0,0.0,...,-0.000087,-0.000512,0.001217,-0.001170,0.000048,-0.000641,-0.000222,-0.000150,-0.000989,-0.001110
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-3.0,0.0,...,0.000928,-0.000621,-0.000058,-0.000816,0.001205,0.001002,0.001207,-0.001065,-0.001207,0.000710
2,1.0,1.0,64.0,0.0,64.0,64.0,64.0,64.0,-3.0,0.0,...,-0.000665,0.001205,-0.001008,0.000255,0.000673,0.000888,-0.000921,-0.000878,-0.000693,-0.000846
3,1.0,1.0,194.0,0.0,194.0,194.0,194.0,194.0,-3.0,0.0,...,0.000328,-0.000442,0.001129,-0.000693,0.000423,0.001189,-0.000228,0.000949,0.000365,-0.001159
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-3.0,0.0,...,-0.052130,-0.017183,-0.048043,0.007814,-0.021623,-0.008897,0.004756,-0.010223,-0.035678,-0.000734

### Validation

In [14]:
start = datetime.now()

X_validation = pd.read_csv(X_validation_filename_csv, dtype=np.float32)

#print(f'Load Features (test) process took {datetime.now() - start} seconds.')

In [15]:
X_validation.head()

,n_[0]-agg-any,n_[0]-agg-all,n_[0]-agg-mean,n_[0]-agg-var,n_[0]-agg-min,n_[0]-agg-max,n_[0]-agg-median,n_[0]-agg-sum,n_[0]-agg-kurtosis,n_[0]-agg-skewness,...,par_vec_390,par_vec_391,par_vec_392,par_vec_393,par_vec_394,par_vec_395,par_vec_396,par_vec_397,par_vec_398,par_vec_399
0,1.0,1.0,1300.0,0.0,1300.0,1300.0,1300.0,1300.0,-3.0,0.0,...,0.000920,0.000513,0.000673,0.000563,-0.000235,0.000153,0.000310,-0.000025,-0.000607,-0.000569
1,1.0,1.0,2.0,0.0,2.0,2.0,2.0,2.0,-3.0,0.0,...,-0.000395,-0.000041,0.000153,0.001183,-0.000362,0.001070,0.000213,0.000716,-0.000671,-0.000646
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-3.0,0.0,...,-0.015543,-0.021048,-0.028767,0.059563,-0.033284,0.011447,0.027921,-0.012893,0.033924,-0.025231
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-3.0,0.0,...,-0.000454,-0.000267,-0.000305,0.000184,0.001101,0.000578,-0.001127,-0.000598,0.000540,0.000092
4,1.0,1.0,143.0,0.0,143.0,143.0,143.0,143.0,-3.0,0.0,...,0.000558,0.000128,-0.000937,0.000696,0.000173,0.000993,0.000966,-0.000054,-0.001227,0.000102

### Test

In [16]:
start = datetime.now()

X_test = pd.read_csv(X_test_filename_csv, dtype=np.float32)

#print(f'Load Features (test) process took {datetime.now() - start} seconds.')

In [17]:
X_test.head()

,n_[0]-agg-any,n_[0]-agg-all,n_[0]-agg-mean,n_[0]-agg-var,n_[0]-agg-min,n_[0]-agg-max,n_[0]-agg-median,n_[0]-agg-sum,n_[0]-agg-kurtosis,n_[0]-agg-skewness,...,par_vec_390,par_vec_391,par_vec_392,par_vec_393,par_vec_394,par_vec_395,par_vec_396,par_vec_397,par_vec_398,par_vec_399
0,1.0,1.0,582.0,0.0,582.0,582.0,582.0,582.0,-3.0,0.0,...,-0.001120,-0.000572,0.001053,0.001110,0.000706,-0.000044,0.000251,-0.000382,-0.000721,0.000295
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-3.0,0.0,...,0.000986,0.000700,-0.000893,0.001189,-0.000353,-0.001173,0.000108,-0.001086,0.000644,0.001170
2,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,-3.0,0.0,...,-0.000923,0.000220,-0.000453,0.000591,0.000940,-0.001001,0.000347,-0.000114,0.000702,0.000899
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-3.0,0.0,...,0.000822,0.000997,-0.000091,0.000756,0.000986,-0.000498,0.001193,0.000040,-0.000690,-0.000304
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-3.0,0.0,...,0.000102,-0.000050,-0.000447,0.000823,-0.001210,0.000877,0.000117,-0.000294,-0.000614,0.000833

### Synthetic Test

In [18]:
#start = datetime.now()

#X_test_synthetic = pd.read_csv(X_test_synthetic_filename_csv, dtype=np.float32)

#print(f'Load Features (test) process took {datetime.now() - start} seconds.')

In [19]:
#X_test_synthetic.head()

## Impute NaN values with feature means

In [20]:
start = datetime.now()

train_columns_means = pd.DataFrame(X_train.mean()).transpose()

#print(f'Transpose process took {datetime.now() - start} seconds.')

In [21]:
start = datetime.now()

X_train.fillna(train_columns_means.iloc[0], inplace=True)
X_validation.fillna(train_columns_means.iloc[0], inplace=True)
X_test.fillna(train_columns_means.iloc[0], inplace=True)

#X_test_synthetic.fillna(train_columns_means.iloc[0], inplace=True)

train_columns_means=None

#print(f'FillNA process took {datetime.now() - start} seconds.')

In [22]:
import os

# list of target parquet files
paths = [
    '../custom_data/processed/train.parquet',
    '../custom_data/processed/validation.parquet',
    '../custom_data/processed/test.parquet',
#    '../custom_data/processed/test_synthetic.parquet',
]

# remove any that already exist
for path in paths:
    if os.path.exists(path):
        os.remove(path)
        print(f"Removed existing file: {path}")

Removed existing file: ../custom_data/processed/train.parquet
Removed existing file: ../custom_data/processed/validation.parquet
Removed existing file: ../custom_data/processed/test.parquet
Removed existing file: ../custom_data/processed/test_synthetic.parquet

In [23]:
start = datetime.now()

X_train.to_parquet('../custom_data/processed/train.parquet', engine='pyarrow', compression='snappy')
X_validation.to_parquet('../custom_data/processed/validation.parquet', engine='pyarrow', compression='snappy')
X_test.to_parquet('../custom_data/processed/test.parquet', engine='pyarrow', compression='snappy')

#X_test_synthetic.to_parquet('../custom_data/processed/test_synthetic.parquet', engine='pyarrow', compression='snappy')

#print(f'Save parquet process took {datetime.now() - start} seconds.')

In [24]:
print(f'Completed at {datetime.now()}.')

Completed at 2025-05-16 12:13:24.276867.