In [1]:
from datetime import datetime
import os
import time

import numpy as np
import pandas as pd

In [2]:

from sherlock.functional import extract_features_to_csv
from sherlock.features.paragraph_vectors import initialise_pretrained_model, initialise_nltk
from sherlock.features.preprocessing import (
    #extract_features,
    #convert_string_lists_to_lists,
    prepare_feature_extraction,
    load_parquet_values,
)
from sherlock.features.word_embeddings import initialise_word_embeddings

unable to import 'smart_open.gcs', disabling that module

In [3]:
print(f'Started at {datetime.now()}.')

Started at 2025-05-25 14:54:48.308788.

In [4]:
prepare_feature_extraction()

Preparing feature extraction by downloading 4 files:

 ../sherlock/features/glove.6B.50d.txt,
 ../sherlock/features/par_vec_trained_400.pkl.docvecs.vectors_docs.npy,

 ../sherlock/features/par_vec_trained_400.pkl.trainables.syn1neg.npy, and
 ../sherlock/features/par_vec_trained_400.pkl.wv.vectors.npy.

All files for extracting word and paragraph embeddings are present.

In [5]:
if not os.path.exists('../sherlock/features/par_vec_trained_400.pkl.docvecs.vectors_docs.npy'):
    raise SystemExit(
        """
        Trained paragraph vectors do not exist,
        please run the '01-train-paragraph-vector-features' notebook before continuing
        """
    )

In [6]:
# ensure embedding initialisation is outside of timing for extract_features
prepare_feature_extraction()
initialise_word_embeddings()
initialise_pretrained_model(400)
initialise_nltk()

Preparing feature extraction by downloading 4 files:

 ../sherlock/features/glove.6B.50d.txt,
 ../sherlock/features/par_vec_trained_400.pkl.docvecs.vectors_docs.npy,

 ../sherlock/features/par_vec_trained_400.pkl.trainables.syn1neg.npy, and
 ../sherlock/features/par_vec_trained_400.pkl.wv.vectors.npy.

All files for extracting word and paragraph embeddings are present.
Initialising word embeddings
Initialise Word Embeddings process took 0:00:02.738091 seconds.
Initialise Doc2Vec Model, 400 dim, process took 0:00:01.376513 seconds. (filename = ../sherlock/features/par_vec_trained_400.pkl)
Initialised NLTK, process took 0:00:00.192506 seconds.

[nltk_data] Downloading package punkt to /Users/omad/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /Users/omad/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [8]:
timestr = time.strftime("%Y%m%d-%H%M%S")

# Saving processed files
X_train_filename_csv = f'../custom_data/processed/train_{timestr}.csv'
X_test_filename_csv = f'../custom_data/processed/test_{timestr}.csv'
X_validation_filename_csv = f'../custom_data/processed/validation_{timestr}.csv'

#X_test_synthetic_filename_csv = f'../custom_data/processed/test_synthetic_{timestr}.csv'

# Extract Features to csv file

### Training

In [9]:
values = load_parquet_values("../custom_data/raw/train_data.parquet")

extract_features_to_csv(X_train_filename_csv, values)

values = None

Starting ../custom_data/processed/train_20250525-145500.csv at 2025-05-25 14:55:05.915689. Rows=318, using 10 CPU cores
Exporting 1588 column features
Finished. Processed 318 rows in 0:00:01.968771, key_count=4

### Validation

In [10]:
values = load_parquet_values("../custom_data/raw/validation_data.parquet")

extract_features_to_csv(X_validation_filename_csv, values)

values = None

Starting ../custom_data/processed/validation_20250525-145500.csv at 2025-05-25 14:55:15.561094. Rows=106, using 10 CPU cores
Exporting 1588 column features
Finished. Processed 106 rows in 0:00:00.900944, key_count=2

### Test

In [11]:
values = load_parquet_values("../custom_data/raw/test_data.parquet")

extract_features_to_csv(X_test_filename_csv, values)

values = None

Starting ../custom_data/processed/test_20250525-145500.csv at 2025-05-25 14:55:18.242029. Rows=107, using 10 CPU cores
Exporting 1588 column features
Finished. Processed 107 rows in 0:00:00.834458, key_count=2

## Read locally processed features

### Train

In [12]:
start = datetime.now()

X_train = pd.read_csv(X_train_filename_csv, dtype=np.float32)

#print(f'Load Features (test) process took {datetime.now() - start} seconds.')

In [13]:
X_train.head()

,n_[0]-agg-any,n_[0]-agg-all,n_[0]-agg-mean,n_[0]-agg-var,n_[0]-agg-min,n_[0]-agg-max,n_[0]-agg-median,n_[0]-agg-sum,n_[0]-agg-kurtosis,n_[0]-agg-skewness,...,par_vec_390,par_vec_391,par_vec_392,par_vec_393,par_vec_394,par_vec_395,par_vec_396,par_vec_397,par_vec_398,par_vec_399
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-3.0,0.0,...,-0.000030,0.000996,0.000097,0.000115,-0.000281,0.001104,-0.001098,-0.000026,0.000633,-0.000720
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-3.0,0.0,...,-0.000071,0.000588,0.000041,-0.001117,-0.000806,0.001206,-0.000884,0.000484,0.000647,-0.000447
2,1.0,1.0,8.0,0.0,8.0,8.0,8.0,8.0,-3.0,0.0,...,-0.000101,-0.000353,-0.001124,-0.000901,-0.000986,-0.000457,0.000312,0.000938,-0.001160,0.001227
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-3.0,0.0,...,-0.016940,-0.034096,-0.036504,-0.004196,-0.029485,0.002654,0.034968,-0.013826,0.023745,-0.059745
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-3.0,0.0,...,-0.000068,0.001075,0.000598,-0.000526,0.000746,-0.000163,0.000062,0.001071,-0.001040,0.000765

### Validation

In [14]:
start = datetime.now()

X_validation = pd.read_csv(X_validation_filename_csv, dtype=np.float32)

#print(f'Load Features (test) process took {datetime.now() - start} seconds.')

In [15]:
X_validation.head()

,n_[0]-agg-any,n_[0]-agg-all,n_[0]-agg-mean,n_[0]-agg-var,n_[0]-agg-min,n_[0]-agg-max,n_[0]-agg-median,n_[0]-agg-sum,n_[0]-agg-kurtosis,n_[0]-agg-skewness,...,par_vec_390,par_vec_391,par_vec_392,par_vec_393,par_vec_394,par_vec_395,par_vec_396,par_vec_397,par_vec_398,par_vec_399
0,1.0,1.0,79.0,0.00,79.0,79.0,79.0,79.0,-3.0,0.0,...,0.000241,-0.000820,0.000229,-0.000056,-0.001210,0.000061,-0.001240,0.001198,-0.000205,-0.000057
1,1.0,1.0,66.5,1892.25,23.0,110.0,66.5,133.0,-2.0,0.0,...,-0.023454,-0.042149,-0.020262,-0.018027,-0.096698,0.002174,0.059239,-0.006348,0.071292,-0.108091
2,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,-3.0,0.0,...,0.000112,-0.000830,0.000534,0.000858,-0.001241,-0.000060,-0.001090,0.001188,-0.000889,-0.001195
3,1.0,1.0,3.0,0.00,3.0,3.0,3.0,3.0,-3.0,0.0,...,-0.016709,0.005426,-0.019394,0.013505,-0.100444,-0.016420,-0.002124,0.009302,0.043159,-0.027781
4,1.0,1.0,27.0,0.00,27.0,27.0,27.0,27.0,-3.0,0.0,...,-0.000490,0.000354,-0.000246,-0.000831,-0.000476,-0.000778,-0.000290,-0.000296,-0.000385,0.000224

### Test

In [16]:
start = datetime.now()

X_test = pd.read_csv(X_test_filename_csv, dtype=np.float32)

#print(f'Load Features (test) process took {datetime.now() - start} seconds.')

In [17]:
X_test.head()

,n_[0]-agg-any,n_[0]-agg-all,n_[0]-agg-mean,n_[0]-agg-var,n_[0]-agg-min,n_[0]-agg-max,n_[0]-agg-median,n_[0]-agg-sum,n_[0]-agg-kurtosis,n_[0]-agg-skewness,...,par_vec_390,par_vec_391,par_vec_392,par_vec_393,par_vec_394,par_vec_395,par_vec_396,par_vec_397,par_vec_398,par_vec_399
0,1.0,1.0,3.0,0.0,3.0,3.0,3.0,3.0,-3.0,0.0,...,-0.000694,-0.000389,-0.000585,0.001201,-0.000440,0.000911,-0.000089,-0.000039,0.000927,-0.000178
1,1.0,1.0,113.0,0.0,113.0,113.0,113.0,113.0,-3.0,0.0,...,-0.000876,0.000062,-0.000539,-0.000958,-0.001209,-0.001086,-0.000595,0.001145,0.000697,-0.000027
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-3.0,0.0,...,-0.000976,-0.000952,0.000785,-0.000304,0.000710,-0.000289,-0.000755,-0.000111,-0.000096,0.001227
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-3.0,0.0,...,-0.016940,-0.034096,-0.036504,-0.004196,-0.029485,0.002654,0.034968,-0.013826,0.023745,-0.059745
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-3.0,0.0,...,0.000127,-0.000990,-0.000223,0.000796,-0.000511,-0.001105,-0.000689,-0.000304,-0.000766,0.000210

## Impute NaN values with feature means

In [18]:
start = datetime.now()

train_columns_means = pd.DataFrame(X_train.mean()).transpose()

#print(f'Transpose process took {datetime.now() - start} seconds.')

In [19]:
start = datetime.now()

X_train.fillna(train_columns_means.iloc[0], inplace=True)
X_validation.fillna(train_columns_means.iloc[0], inplace=True)
X_test.fillna(train_columns_means.iloc[0], inplace=True)

#X_test_synthetic.fillna(train_columns_means.iloc[0], inplace=True)

train_columns_means=None

#print(f'FillNA process took {datetime.now() - start} seconds.')

In [20]:
import os

# list of target parquet files
paths = [
    '../custom_data/processed/train.parquet',
    '../custom_data/processed/validation.parquet',
    '../custom_data/processed/test.parquet',
#    '../custom_data/processed/test_synthetic.parquet',
]

# remove any that already exist
for path in paths:
    if os.path.exists(path):
        os.remove(path)
        print(f"Removed existing file: {path}")

Removed existing file: ../custom_data/processed/train.parquet
Removed existing file: ../custom_data/processed/validation.parquet
Removed existing file: ../custom_data/processed/test.parquet

In [21]:
start = datetime.now()

X_train.to_parquet('../custom_data/processed/train.parquet', engine='pyarrow', compression='snappy')
X_validation.to_parquet('../custom_data/processed/validation.parquet', engine='pyarrow', compression='snappy')
X_test.to_parquet('../custom_data/processed/test.parquet', engine='pyarrow', compression='snappy')

#X_test_synthetic.to_parquet('../custom_data/processed/test_synthetic.parquet', engine='pyarrow', compression='snappy')

#print(f'Save parquet process took {datetime.now() - start} seconds.')

In [22]:
print(f'Completed at {datetime.now()}.')

Completed at 2025-05-25 14:56:02.207950.